### ISSUE TITLE
Application error during authorization process

### ISSUE THREAD

**Issue by ryanwelcher** [emersonthis/instagramtoken.com#1]
After correctly entering my Client ID, Client Secret this error page is displayed after the step of authorizing the app is confirmed.

![application_error](https://user-images.githubusercontent.com/1259027/28284295-7b9bde80-6afe-11e7-8da0-c46517e3d7a6.png)

**Comment by emersonthis** [comment]
Confirmed. I'm looking into it.

As a temporary workaround, log into Instagram first and then submit the token request. It seems to work without error when I do that. If the workaround works for you too, please let me know.

**Comment by ryanwelcher** [comment]
Thanks for getting back to me so quickly. That worked.

I was logged into the developer site but needed to have a window with instagram.com open it seems

**Comment by emersonthis** [comment]
Thanks for letting me know. It should work when you're logged out too, but obviously something is wrong. I just had to upgrade node in a hurry due to a security hole that was announced. I'm guessing that's connected to this issue. More soon.

**Comment by emersonthis** [comment]
Looks like the node update might have changed the value of `req.headers.referer` so it was returning the Instagram login URL instead of `https://instagramtoken.com`. Should be fixed now. Thanks for reporting!
